---
- name: Ensure CUDA environment variables are set
  blockinfile:
    path: "~/.bashrc"
    block: |
      export PATH=/usr/local/cuda-12.8/bin:$PATH
      export LD_LIBRARY_PATH=/usr/local/cuda-12.8/lib64:$LD_LIBRARY_PATH
  when: nvcc_check.rc != 0

- name: Reload bashrc
  shell: "source ~/.bashrc"
  args:
    executable: /bin/bash
  when: nvcc_check.rc != 0